// strings from yyyyyyy.info, w1red.neocities.org, archive
var text_yyyyyyy = [
  "�_�@|�@�@�@�@ �E�@�E�@�@ |�@���@ �i�P�P�P�P�P�P�P�P�P|�@�@�@�@ �j� ＠ ＠ ＠ �",
  "???????? ???? ?? ????? X????? ?????? ???????? ??????E????Ȃ?? ?????? ?????? ??????.",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| ● | | /l/ ,-== =＼ヾ| ＼ | ●",
  "�y20k�{�ɁzCore 2 Duo ���� T-Banana�T�[�o�",
  "REMEMBER: NEVER GIVE OUT YOUR PERSONAL INFORMATION SUCH AS YOUR NAME, HOME ADDRESS, SCHOOL NAME, OR TELEPHONE NUMBER IN A CHAT ROOM OR ON BULLETIN BOARDS. ALSO, NEVER NEVER SEND A PICTURE OF YOURSELF TO SOMEONE YOU CHAT WITH ON THE COMPUTER WHO HAS MADE YOU FEEL UNCOMFORTABLE OR S",
  "↷ .www.www.www.「￣￣￣￣fff . G ?M ??? ▬▬",
  "rs_marquee(\"???‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Ä",
  "I remember it having a really eerie feel to it, and some themes about destruction and being thrown away or lost. Hard for a little one! It also made m",
  "plz all plz help i dont wanna throw my computer away :(",
  "�y�^�p�|���V�[/�ƐӂȂǁz?? ? ? ?? @pitää.k PPPPPPPPPP.¯¯¯¯÷˜??????? ??? ??? ???? ????",
  "For these same rays extended between the eye and the plane seen come together very quickly by their own force and by a certain marvellous subtlety, penetrating the air and thin and clear objects they s",
  "??????????????? ? afk mcm .//// .? ?? ???? ? ??????? ? ? ?? ?? ?? ???????? ? ?? ?????",
  "Stay still for 10 seconds and all the doors will open. Stay still for 145 seconds and all the walls will turn into exits.",
  "This is a look down a street, in a town that is not even close to being finished. It's going to be hu",
  "WARNING IF YOU DONT READ THE README.TXT IT WILL DELETE YOUR SYSTEM32 FOLDER. THIS IS BAD. SO READ THE README.TXT.",
  "?? ? ????????? ? ? ?????? ? ???????? ?? ? ? ? ? ??▒▒▒▒▒▒▒▒▒▒▒▒??????^^^^^」??????̃R???N?V?????́A???ׂē????̐F?t???ŕ????i?A?͑??i?ł͂??????܂???B???ׂĈ?_??̂ł??B",
  "Information: True / False",
  "Remember me on this computer √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©‚Äû√Ñ√• ‚Äû√Ñ√Ñ√î¬∫√†√î¬∫√∏/√î¬∫œÄ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√",
  "Do you use Picasa Web Albums or another photo service?",
  "I think there are 3 possibilities of this sight &gt;someone fucked up a code &gt;someone knew exactly what they were doing and had A LOT of free time &gt;secret trading sight for secret data",
  "@／ ／ ＼ ＼@�@.;�@´ ;,il||iγ �@�@�@�",
  "Stay still for 10 seconds and all the doors will op",
  "?? ? ????????? ? ? ?????? ? ???????? ?? ? ? ? ? ??▒▒▒▒▒▒▒▒▒▒▒▒??????^^^^^」??????̃R???N?V?????́A???ׂē",
  "rs_marquee(\"???‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√�",
  "√î√∏Œ©¬ª√á¬´√á¬ª√á¬´√ÖA√î�",
  "Time is precious. Both guys and gals have better things to do rather than hanging out in the computer room.",
  "This is inside my imaginary house, at t",
  "�_�@|�@�@�@�@ �E�@�E�@�@ |�@���@ �i�P�P�P�P�P�P�P�P�P|�@�@�@�@ �j� ＠ ＠ ＠ └──�",
  "To all of my friends, It looks like someone has hacked into my e-mail account and sent something, but I am unable to pick it up and see what it was. I am o",
  "Time is precious. Both guys and g",
  ":|∴????¿¿?¿€?@?@?ÒÒÒÒÒÒOZ??:�E:�E�j���i∴;;|:;(�@�@ WWWWWWWWWWWWWWWWW �@�@�@�@�@ �@�@�@�@);; |�F��_�Q�Q�^;|;:�i �Q� Q�Q�Q�Q�Q�l�_�E:�F:;�_�∴::�::(�@�@�",
  "3♥, 10♣, A♦, 2♠, 3♦10♠, 5♣6♠, 4♥▚▚▚▚K9♣, Q♠7♦, Q ♣I am now in the basement level of building 3—in the supercomputer room—and I can't seem t",
  "????? ?? ? ?? ????? ? ?????√î√∏Œ©y√",
  "I remember it having a really eerie feel to it, and s",
  "///////lnev Nev NEV`√î√∏Œ©√î�",
  "???? , , , lzll ノ’ ゛ ゝ ー ＜◎＞、＜◎＞ ノ（． ．）ヽ |トェェェェイ @�@�@�@�@�@�@�@�@�@�@ �@�@�Q�Q�Q ���@ √î√∏Œ©√�",
  "This is a look down a street, in a town that is not even close to being finished. It's going to be huge, an entire town, I can't wait to make it, just don't have as much time as I used to.",
  "I think there are 3 possibilities of this sight &gt;someone fucked up a code &gt;someone knew exactly what they",
  "NEVER GIVE OUT YOUR PERSONAL INFORMATION SUCH AS YOUR NAME, HOME ADDRESS, SCHOOL NAME, OR TELEPHONE NUMBER IN A CHAT ROOM OR ON BULLETIN BOARDS. ALSO, NEVER NEVER SEND A PICTURE OF YOURSELF",
  ":|∴????¿¿?¿€?@?@?ÒÒÒÒÒÒOZ??:�E:�E�j���i∴;;|:;(�@�@ WWWWWWWWWWWWWWWWW �@�@�@�@�@ �@�@�@�@);; |�",
  "√î√∏Œ© √î√∏Œ©√î√∏Œ©√î√∏Œ© √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ© IJ ??¬¨¬®",
  "√î√∏Œ©¬ª√á¬´√á¬ª√á¬´√ÖA√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î",
  "GIF89a‚Äì¬∞‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äì‚àè‚Äì‚àè‚Äì‚àè!‚Äö√†√¥‚Äì¬®?‚Äì�",
  "Remember me on this computer √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©‚Ä",
  "PRLFo‚Äö√∂√á,EW",
  "REPOST THIS!!!!!",
  "If you have any ad blocking software running, please disble it",
  "This is inside my",
  "‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/√î√¶√úY}‚Äû√Ñ√Ñ.:',√îŒ©¬Æt:√î√¶√â√î√¶√™‚Äû√Ñ√Ö‚Äû√Ñ√¢ : ,f‚Äö√Ñ√™t:√î√¶√â√î√¶√™‚Äû√Ñ√Ö ‚Äû√Ñ√§f‚Äû√âŒ�",
  "I am now in the basement level of building 3—in the supercomputer room—and I can't seem to get to Outer-Heaven.",
  "REMEMBER: NEVER GIVE OUT YOUR PERSONAL INFORMATION SUCH AS YOUR NAME, HOME ADDRESS, SCHOOL NAME, OR TELEPHONE NUMBER IN A CHAT ROOM OR ON BULLETIN BOARDS. ALSO, NEVER NEVER SEND A PICTURE OF YOURSELF TO SOMEONE YOU CHAT WITH ON THE COM",
  ":|∴????¿¿?¿€?@?@?ÒÒÒÒÒÒOZ??:�E:�E�j���i∴;;|:;(�@�@ WWWWWWWWWWWWWWWWW �@�@�@�@�@ �@�@�@�@);; |�F��_�Q�Q�^;|;:�i �Q� Q�Q�Q�",
  "????? ?? ? ?? ????? ? ?????√î√∏Œ©y√î√∏Œ©^√î√∏Œ©p√î√∏Œ©|√",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| �",
  "I remember it having a really eerie feel to it, and some themes about destruction and being thrown away or lost. Hard for a little one! It also made me confused about inanimate objects; I began to worry about how I affected their feelings. All in all, it made me feel very anxious.\"",
  "REMEMBER: NEVER GIVE OUT YOUR PERSONAL INFORMATION SUCH AS YOUR NAME, HOME ADDRESS, SCHOOL NAME, OR TELEPHONE NUMBER IN A CHAT ROOM OR ON BULLETIN BOARDS. ALSO, NEVER NEVER SEND A PICTURE OF YOURSELF TO SOMEONE YOU CHAT WITH ON THE COMPUTER WHO HAS MADE YOU FEEL UNCOMFORTABLE OR SCARED.╪",
  "* √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©z√î√∏Œ©M√î√∏Œ©T√î√∏Œ©C√î√∏Œ©g√î√∏Œ©√É√¢^√î√∏Œ©c * √î√∏Œ©A√î√∏Œ©b√î√∏Œ©v√î√∏Œ©√î√∏Œ©√î√∏Œ©[√î√∏Œ©_√î√∏Œ©√É�",
  "#! /bin/sh# reiserfs v3 denial of \"00000000\" creation attack (ha# insider: EHASHCOLL",
  "CP(R)U(N.THERE)? √î¬∫‚Ä¢√î¬∫¬∞√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫",
  "????? ?? ? ?? ????? ? ?????√î√∏Œ©y√î√∏Œ©^√î√∏Œ©p√î√∏Œ©|√î√∏Œ©√î√∏Œ©√î√∏Œ©V√î√∏Œ©[/√î√∏Œ©‚àÜ√™‚Äù√á¬ª√á¬´√Öz?? ? ? ??? ? ??????? ?? ? ??????????√î√∏Œ©√î√∏Œ©??? ? ? ?? ? ?? ???? ?? √î√∏Œ©√î√∏Œ©√î√∏Œ© √î√∏Œ©√î√∏Œ© √î√∏Œ©? ??? ?????? ??? ????????? ? ? ? ???????? ? ?",
  "@／ ／ ＼ ＼@�@.;�@´ ;,il||iγ �@�@�@�@�@�@ �@ �@ �@ �@ �@ /�",
  "‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/√î√¶√úY}‚Äû√Ñ√Ñ.:',√îŒ©¬Æt:√î√¶√â√î√¶√™‚Äû√Ñ√Ö‚Äû√Ñ√¢ : ,f‚Äö�",
  "Fantasy Ocean",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| ● | | /l/ ,-== =＼ヾ| ＼ | ● （",
  "2019699603 002031447061RUPASOV=\" touch $idonetouch $ATTACKif [ \\! -f $ATTACK ] ; then echo \"FATAL: can't create $ATTACK\"firm -f $RUPASOV $R5 $TEA Dec 28 23:38:24 kotzmaster kernel: ReiserFS: loop0: Using rupasov hash to sort namesDe",
  "You must either brain dump via neural hookup or the process must keep in contact with your intelligence back at your console.",
  "??`?V????? ‚Äπ√á???B?T? ‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≤√≠L L\\‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚",
  "I believe right before this she is following what she thinks is a sure path, and the sweeper dog comes along and erases it. Then she starts crying, and all the weird, unnatural animals start crying, then they start to be cute, but they just disappear, then the moon turns into a cat. None of it is right and a little girl is sad, and scared, and alone. too creepy.",
  "(@, &amp;, %, *, etc.)",
  "???? , , , lzll ノ",
  "This is inside my imaginary house, at the moment this is the only room that's finished, unless you count stairs and hallways. I had plants in the corner but took them out as they took about a week to render.",
  "████████████████████████████████████████████████████████████████████████████████████████?????Љ?i?͂܂??Q?O?O?V?N?Q???P??ɕς",
  "/ ヽﾊ ､ ヽ 〃 {_{ ＼ 、／,ﾘ| ｌ │ i| ﾚ!小ｌ从 |、i| ﾚ⊂⊃ ､_,､_ |ﾉ ヽ、 ゝ._） j / ／ ／\" ｀ヽ",
  "Email me quickly for I may lose this account any day now",
  "NEVER GIVE OUT YOUR PERSONAL INFORMATION SUCH AS YOUR NAME, HOME ADDRESS, SCHOOL NAME, OR TELEPHONE NUMBER IN A CHAT ROOM OR ON BULLETIN BOARDS. ALSO, NEVER NEVER SEND A PICTURE OF YOURSELF TO SOMEONE YOU CHAT WITH ON THE COMPUTER WHO HAS MADE YOU FEEL UNCOMFORTABLE OR SCARED.╪",
  "l&#65438;&#65438;&#65438;&#65438;&#65438;llllllllll!!&#65438;: : ,,illlll!&#65438;&#8242;.`&#65438;!!llllllii,,,,_&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288; ,,,iiillllllllll!!!&#65438;&#65438;&#12443; &#12288; : llllli,.\\'lllllll&#12289;&#12288;.,,iilll!!&#65438;liiiilllllllllll: &#65438;&#65438;!",
  "＼ / ＼ 丶 i. | / ./ ／ ＼ ヽ i. .| / / ／ �",
  "@／ ／ ＼ ＼@�@.;�@´ ;,il||iγ �@�@�@�@�@�@ �@ �@ �@ �@ �@ /�||lii|li||,;,.il|i;,�@; . ., ,li�@�@�@'�@;�@�@ .`",
  "1. To yourself, say the name of the only guy or girl you wanna be with 3 times2. Think of something you wanna accmplish within the next week and say it to your self 7 times3. If you had 1 wish what would it be? say it to yourself 9 times!!!4. Think of something that you want to happen ♪P.S. DO NOT IGNORE THIS",
  "‚Äö¬®√¥][ ][ ‚Äö¬®√¥oranges",
  "�_�@|�@�@�@�@ �E�@�E�@�@ |�@���@ �i�P�P�P�P�P�P�P�P�P|�@�@�@�@ �j�",
  "I think there are 3 possibilities of this sight",
  "Please wait while we transfer you...",
  "√î√∏Œ©¬ª√á¬´√á¬ª√á¬´√ÖA√î√�",
  "?? ? ????????? ? ? ?????? ? ???????? ?? ? ? ? ? ??▒▒▒▒▒▒▒▒▒▒▒▒??????^^^^^」??????̃R???N?",
  ",;-'''\":::::::::::::::::::::::::\"''-､ . ,／\":::::::::::::_,,,.,,..,.:\"''ｰ;:_::::´＼ . /:::::::::::;:'''\"\"\" .`;:::::::::ヽ /:::::::r''\" '､::::::::::::::i . i::::::r'' ＼:::::▓:::::l ▚▚ l:::::;' \"i:::::::| |::",
  "I accidentally 93 MB of a .rar file what should I do...is this dangerous ?",
  ",;-'''\":::::::::::::::::::::::::\"''-√îŒ©¬ß.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ ,√î¬∫√®\":::::::::::::_,,,.,,..,.:\"''√îŒ©‚àû;:_::::¬¨¬•√î¬∫¬∫.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ /:::::::::::;:'''\"\"\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ.`;:::::::::‚Äû√âŒ©‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/:::::::r''\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ'√îŒ©¬ß::::::::::::::i.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ",
  "This is a clock I modeled after the clock in my basement, I think it looks really cool. It looks just like it, and it only took me a couple days to make. I'm very proud of this one.",
  "??`?V????? ‚Äπ√á???B?T? ‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≥¬∫‚Äö√≤√≠L L\\‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠`‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö",
  "Stay still for 10 seconds and all the doors will open. Stay still for 145 seconds and all the walls will turn into",
  "‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/√î√¶√úY}‚Äû√Ñ√Ñ.:',√îŒ©¬",
  "I believe right",
  ",;-'''\":::::::::::::::::::::::::\"''-√îŒ©¬ß.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ ,√î¬∫√®\":::::::::::::_,,,.,,..,.:\"''√îŒ©‚àû;:_::::¬¨¬•√î¬∫¬∫.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ /:::::::::::;:'''\"\"\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ.`;:::::::::‚Äû√âŒ©‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/:::::::r''\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√�",
  ".................................... ▚___.. __ｊgｇgｇggｇｇgｇggｇｊｊｊｊquｊ,.,,、 . _,ｇg۞▚▚▚▚▚ڲ▚▚▚▚雛▚▚ن ng.. ...,ｊ▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚齟g,,,、 _,,,g▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚ ð. . ､ｊ[▚▚▚▚▚▚▚▚▚▚▚▚▚▚T▚▚▚▚▚▚▚▚ｇgｊ,...",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| ● | | /l/ ,-== �",
  "�킸��킵���ݒ��͂��ׂ☆�Big-server���s���R�[�X�ł��B♪!���ł����Őݒ�ł��� root����t�������f�B�X�N�e�� ���[�� �^�Zz ?█△ ?SS██ HELLO♪ ii ■▲▼?畜 ?????`?????肵???B???[???b ?p?e?n?ŐA????͑??݂??邪 ?A??????͂ŏG?ł?",
  "─ ─ .| ┼ ７二 ,┴､ l l ￣ﾌ | ─っ゛ ┼ ┼,-､ （___ （___ しα |_目_| |二| し _人_ |／ &lt;_ ９ ｲ α -┴-┌┴┐ ┼ 三|ヨ キ ￣ ┼ 丶＼／ ─┼─ キ ／ ┼丶 ￣ﾌ / ─っ゛ ┼ ┼,-､ 乂 子 と 百 ヽ ＿ ｑ＿ （＿ .／＼ ヽ ＼ α 。) /V &lt;_ ９ ｲα",
  "\\\"I love to tou",
  "＿＿. ／ ーヽ､ / / ￣￣~ヽ / ト､.,.. ＼. =彳 ＼＼ ヽ / ＼＼ | | /⌒ヽ ヽ | | ｜ | | / | ｜ ヽ|／ | ｜ |＿＿＿＿＿ヽ _.＿_ lヽ,,lヽ _| ::|_ | |Θ|( |￣￣￣|￣￣|＿ |_|＿|と i |＿＿＿|＿＿|＿| |_| しーJ",
  "l&#65438;&#65438;&#65438;&#65438;&#65438;llllllllll!!&#65438;: : ,,illlll!&#65438;&#8242;.`&#65438;!!llllllii,,,,_&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288; ,,,iiillllllllll!!!&#65438;&#65438;&#12443; &#12288; : llllli,.\\'lllllll&#12289;&#12288;.,,iilll!!&#65438;liiiilllllllllll: &#65438;&#65438;!lllllllllliii,,,,,&#12289;&#12288;&#12288;&#12288;&#12288;&#12288;&#12288; .,,,,iillllll!lllll",
  "�_�@|�@�@�@�@ �E�@�E�@�@ |�@���@ �i�P�P�P�P�P�P�P�P�P|�@�@�@�@ �j� ＠ ＠ ＠ └────┘ ／ ＼:＼ ♪ .Y Z X ﾐ:::| ♪ ﾐ|_≡=､´ ｀, ≡=_、 |;/ .,,,,,,,,,,,,,,,,,,, ||..● .|￣|. ● |─/ヽ ＼ ヽ,,,,,,,,,～♪/／ |ヽ二/ ＼二/",
  "Ok so computer says limited or no connectivity or Invalid. IP Address . When I click on general tab it shows 700 out of 700 packets received. Signal strenghth is good as well. It feels like something little is just preventing me from accessing the web or fully connecting to the web",
  "‚Äö√Ñ√ª¬¨√ò‚Äö√Ñ√ª () _+ SOFTWARE UPDATTE",
  "No one would deny that the painter has nothing to do with things that are not visible. The painter is concerned solely with representing what can be seen.",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| ● | | /l/ ,-== =＼ヾ| ＼ | ● （:::::::/彡彡彡彡 ミミミミ :::::::::） ● （://￣￣�",
  "|::::::::::::::::::::::::::::::::::::::::::::::||‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ √î¬∫√∏|√î¬∫√∏_√î¬∫√∏ |‚Äû√Ñ√Ñ |‚Äû√Ñ√Ñ | |::::::::::::::::::::::::::::::::::::::::::::::||‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ|r- _‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ- __ |‚Äû√Ñ√Ñ |‚Äû√Ñ√Ñ | |::::::::::::::::::::::::::::::::::::::::::::::||‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ||‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ - __‚Äû√Ñ√�",
  "You must either brain dump via neural hoo",
  "████████████████████████████████████████████████████████████████████████████████████████?????Љ?i?͂܂??Q?O?O?V?N?Q???P??ɕς??܂??B??",
  "／ __|l l l＼ ＼ ● / /／ ／ ＼ |_L ＼ ＼ ● / /／／ ＼ | l_ ＼ ) ● / （ /.| ＼＼＼ ＼| ● | | /l/ ,-== =＼ヾ| ＼ | ● （:::::::/彡彡彡彡 ミミミミ :::::::::） ● （://￣￣￣￣ヽ== =/￣￣￣￣ヽ ● =ﾛ -=･=- ∥ ∥ -=･=- ﾛ= ● ∥ ／ /ﾉ ヽ ＼ ∥ ● ヽ======/ . ⌒ ｀ ========ﾉ ● . （ .（● ●） ）ﾉ |",
  "????? ?? ? ?? ????? ? ?????√î√∏Œ©y√î√∏Œ©^√î√∏Œ©p√î√∏Œ©|√î√∏Œ©√î√∏Œ©√î√∏Œ©V√î√∏Œ©[/√î√∏Œ©‚àÜ√™‚Äù√á¬ª√á¬´√Öz?? ? ? ??? ? ??????? ?? ? ??????????√î√∏Œ©√î√∏Œ©??? ? ? ?? ? ?? ???? ?? √î√∏Œ©√î√∏Œ©�",
  "* √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©z√î√∏Œ©M√î√∏Œ©T√î√∏Œ©C√î√∏Œ©g√î√∏Œ©√É√¢^√î√∏Œ©c * √î√∏Œ©A√î√∏Œ©b√î√∏Œ©v√î√∏Œ©√î√∏Œ©√î√∏Œ©[√î√∏Œ©_√î√∏Œ©√É√¢^√î√∏Œ©c",
  "3♥, 10♣, A♦, 2♠, 3♦10♠, 5♣6♠, 4♥▚▚▚▚K9♣, Q♠7♦, Q ♣",
  "√î√∏Œ© √î√∏Œ©√î√∏Œ©√î√∏Œ© √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ© IJ ??¬¨¬®¬¨¬®U ! ! ! ! !",
  "/ ヽﾊ ､ ヽ 〃 {_{ ＼ 、／,ﾘ| ｌ │ i| ﾚ!小ｌ从 |、i| ﾚ⊂⊃ ､_,､_ |ﾉ ヽ、 ゝ._） j / ／ ／\" ｀ヽ ヽ ヘ,､ __, イ",
  "GIF89a‚Äì¬∞‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äö√ë√±‚Äì‚àè‚Äì‚àè‚Äì‚àè!‚Äö√†√¥‚Äì¬®?‚Äì‚àû‚Äö√Ø√∂A;‚Äö√Ø‚Ä¢‚Äö√Ø√π8??S‚Äì‚Ä†‚Äî√©‚Äö√Ø√¨)b‚Äö√Æ¬ßP‚Äì¬•*‚Äì¬ßa‚Äö√Æ√•Fp‚Äì¬™‚Äì¬®‚Äì√Ö‚Äì‚à´V‚Äì¬±‚Äö√Ø√Ø‚Äì¬∂&‚Äî√°‚Äö√Æ¬•L*‚Äö√Ø√ªdZ|‚Äì√∫?????? image√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©WEP KEY CET83'visible imageimageimageimage",
  "For these same rays extended between the eye and the plane seen come together very quickly by their own force and by a certain marvellous subtlety, penetrating the air and thin and clear objects they strike against something dense and opaque, where they strike with a point and adhere to the mark they make. Among the ancients there was no little dispute whether these rays come from the eye or the plane. This dispute is very difficult and is quite useless for us. It will not be considered.",
  "???? , , , lzll ノ’ ゛ ゝ ー ＜◎＞、＜◎＞ ノ（． ．）ヽ |トェェェェイ @�@�@�@�@�@�@�@�@�@�@ �@�@�Q�Q�Q ���@ �@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@ �@�@ �^�@�@�@�@ �_ �@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@/�@�@ ∧�@∧�@�_-----________ �_�@|�@/�@__--�P �@�@�@�@�@�@�@�@�@�@�@�@�@�@�@�@--------█ ▓ ÌÌ ¦ ▄░ ▓ÌÌ ▓ ▄█▓█ ░▄░ ¦ Ì░ ░█▓▀▓Ì▀░▀█ Ì ░Ì ▄▀ ▀░¦ ████████ ▀░░¦¦ Ì░¦ ¦ ▀░Ì¦ ¦ ¦░▓ ¦░ ¦ ▓░ ░¦",
  "＼ / ＼ 丶 i. | / ./ ／ ＼ ヽ i. .| / / ／ ＼ ヽ i | / / ／ ＼ ▚▚ -‐ ー _＿ -- 二 ／￣＼ ＝ 二 ￣. | ＾o＾ | ￣ -‐ ＼＿／ ‐- ／ / ヽ ＼ ／ 丶 ＼ ／ / / | i, 丶 ＼ ／ / / | i, 丶 ＼",
  "| ヽ ／ |＿＿ |'\"￣ヽ ヽ!! |,,\" ﾍ ＜ | |ヽ ﾞ!!!､ ,,-' iヽ── / 丿 /|||ｌ ﾞﾞヽ､ｌｌ,,‐''''\"\" | ヽ||||||||| ヽ／|||ｌ ＿＿＿,,,,,, ﾞｌ ,,,,, ＼||||||||| ＿||!' ／ヽ､ ;::''“”“~`ﾞ＞┴＜;''“”~` /＼ |'\"￣| | |＼ ／ |ミﾐヽ──‐'\"ﾉ≡- ﾞ'──''彡| |､ | | | | ￣| |ミミミ／\"~( ,-､ ,:‐､ ) '彡|| |､/ / | | ヽ､ｌ| |ミミミ| |､─＼＼＼＼ |彡ｌ| |/ ／＿ | | ＼/|ｌ |ミミミ| ＼_/￣＼＼＼＼''|ｌ/ ￣／ | | ＼ ﾉ ｌ|ミミミ|",
  "@pit‚àö¬ß‚àö¬ß.k PPPPPPPPPP.¬¨√ò¬¨√ò¬¨√ò¬¨√ò‚àö‚àë√Ä√∫??????? ??? ??? ???? ????",
  "CP(R)U(N.THERE)? √î¬∫‚Ä¢√î¬∫¬∞√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢‚Äö√≥√•√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚Ä¢√î¬∫‚",
  "06:40 pls06:40 I wonder if anyone will read this one day06:40 probably not",
  "(@, &, %, *, etc.)",
  "@／ ／ ＼ ＼@�@.;�@´ ;,il||iγ �@�@�@�@�@�@ �@ �@ �@ �@ �@ /�||lii|li||,;,.il|i;,�@; . ., ,li�@�@�@'�@;�@�@ .`�@.;�@�@�@stst�@il,.;;.:||i�@.i| :;il|l||;(� �@�@�@�@�@ �@�@�@�@�@�@�@�@�@�M;;i|l|li||l����|||il;i:ii,..,.i||l´i,,.;,..�@.il�@�M,�@�@,i|;.,l;;:`ii||iil||il||il||l||i|liiށT",
  "USE WITH CAREFULLY DO NOT DRINK OR USE IT FOR ANY OTHER PURPOSE. YOU CAN USE ISOPROPYL TO CLEAN WOUNDS OR CPU'S OR GPU'S",
  "Remember me on this computer √î√∏Œ©√î√∏Œ©√î√∏Œ©√î√∏Œ©‚Äû√Ñ√• ‚Äû√Ñ√Ñ√î¬∫√†√î¬∫√∏/√î¬∫œÄ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√âŒ© _√î¬∫√†√î¬∫√∏_√î¬∫√¢‚Äû√Ñ√Ñ|‚Äû√Ñ√Ñ|√î¬∫¬∫| ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ|s‚Äö√Æ√≥‚Äö√Æ‚â•‚Äö√Æ√Ö|√î√∏¬£√î√∏¬£√î√∏¬£√î√∏¬£√î√∏¬£|‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ √î¬∫¬∫|. ‚Äö√Æ√á ‚Äû√Ñ√Ñ√îŒ©√∫",
  "\"I love to touch it. I love to hold it. It's in my pocket, right now, in iPod mode, playing that tender new Moby song through its surprisingly good little speaker and keeping my thighs warm and my heart happy. It's also checking the weather in Mumbai. Incredible.\"",
  "＼ / ＼ 丶 i. | / ./ ／ ＼ ヽ i. .| / / ／ ＼ ヽ i | / / ／ ＼ ▚▚ -‐ ー _＿ -- 二 ／￣＼ ＝ 二 ￣. | ＾o＾ | ￣ -‐ ＼＿／ ‐- ／ / ヽ ＼ ／",
  "_,,,--''''''''''''''- ､,,_ ／:::::::::::::::::::::::::::::::::::::ヽ ／:::::::::::::::::::::::::::::::::::::::::::::::） /::::::::::::::::::::::::::::::::::::::::::{Ｅ}::/ /::::::::::::, ---------､______/ 'ｰ'ミ彡ﾆｯｯ,,,, ,,,,ｯｯｪ､ lミ} ﾄy' | | - ; ::.ヽ､_ i｀l . !_l /'､_ __)､ lﾉ",
  "‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≥¬∫‚Äö√≤√≠ ??? ?‚Äö√≤√≠‚Äö√≤√≠`‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠‚Äö√≤√≠ ????W??‚Ä¶√®‚Äì√¢?√à√áŒ© ?Ô¨Ç√™A??",
  "Both religion and the occult derive much of their power from simultaneously simulating and managing dread: the anxieties that dog the perpetually shifting boundaries of the self, and especially the ultimate borderland of death. As new technologies being to remold these very same boundaries, the shadows, doubles, and dark reflections that haunt human identity begin to leak outside the self as well,",
  ".................................... ▚___.. __ｊgｇgｇggｇｇgｇggｇｊｊｊｊquｊ,.,,、 . _,ｇg۞▚▚▚▚▚ڲ▚▚▚▚雛▚▚ن ng.. ...,ｊ▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚齟g,,,、 _,,,g▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚ ð. . ､ｊ[▚▚▚▚▚▚▚▚▚▚▚▚▚▚T▚▚▚▚▚▚▚▚ｇgｊ,... ....ｊ▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚〓▚▚▚▚▚ｊ､ ب 〓▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚▚ s",
  "#! /bin/sh# reiserfs v3 denial of \"00000000\" creation attack (ha# insider: EHASHCOLLISION EAGAIN!#ATTACK=00000000R5=\"000003435823 000022067556 000040799289 000047672563 000001191‚Äö√±√†62858 000125037032 000137894590 000156516313 0000193879879 000209384885 000228006608 000246738340 00000278117621 000296849354 000305480087 000311354361 0000083066683 000504545",
  "FamJ, FamN, FamM, FamRFamJ, FamN, FamM, FamR",
  "l ,r'\"\"￣ﾆ､ .,/／ ヽ、 ／ i ／ _,r\"∠ﾆ､'L- l,,／ l ,rー--－ヽ､ l / ,,r ､ ﾞl /ｦ (＿) ／⌒/⌒i⌒＼(＿＿) ｜ ● ● ｜// ＼／// ＞～～＜_// .ﾉ::[三ﾉ :.'ヽ",
  "＼,,,,,,,,,,,,,,,,,,♪／ /. ハ - －ハ |_/ ！！ 二二二二二二l | | ヽ／ヽ／＼_ノ / 99！！ | | ♪ _________ ♪ | ＼､ ヽ二二／ヽ / | | |◎□◎|. | ＼i ＿＿＿ ／ | | /´￣￣￣￣/⌒ヽ.| /´￣し'￣し' ＼ ///. ￣￣| | |￣￣￣| 、_人_ / 彡 ◎￣￣￣￣￣ | | | | _） ◎彡.| | ハ゛ン | | | | ´｀Ｙ´ .| | ハ゛ン��i�@�@|�@�@�_s�Q�Q�Q�Q�Q�Q�Q�Q �@�P�P�i�P�",
  ",;-'''\":::::::::::::::::::::::::\"''-√îŒ©¬ß.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ ,√î¬∫√®\":::::::::::::_,,,.,,..,.:\"''√îŒ©‚àû;:_::::¬¨¬•√î¬∫¬∫.‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ /:::::::::::;:'''\"\"\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ.`;:::::::::‚Äû√âŒ©‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ/:::::::r''\"‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ'√îŒ©¬ß::::::::::::::i.‚",
  "�킸��킵���ݒ��͂��ׂ☆�Big-server���s���R�[�X�ł��B♪!���ł����Őݒ�ł��� root����t�������f�B�X�N�e� ���[�� �^�Zz ?█△ ?SS██ HELLO♪ ii ■▲▼?畜 ?????`?????肵???B???[???b ?p?e?n?ŐA????͑??݂??邪 ?A??????͂ŏG?ł?",
  "For these same rays extended between the eye and the plane seen come together very quickly by their own force and by a certain marvellous subtlety, penetrating the air and thin and clear objects they strike against something dense and opaque, where they strike with a point and adhere to the mark they make. Among the ancients there was no little dispute whether these rays come from the eye or the p",
  "To all of my friends, It looks like someone has hacked into my e-mail account and sent something, but I am unable to pick it up and see what it was. I am obviously changing my e-mail address and will forward it as soon as possible. Please know that if it was anything distasteful, off-color, or otherwise offensive, it surely did not come from me.",
  "Please take a calm walk and remember the people here are real",
  "Both religion and the occult derive much of their power from simultaneously simulating and managing dread: the anxieties that dog the perpetually shifting boundaries of the self, and especially the ultimate borderland of death. As new technologies being to remold these very same boundaries, the shad",
  "FamJ, FamN, FamM, FamR",
  "For these same rays extended between the eye and the plane seen come together very quickly by their own force and by a certain marvellous subtlety, penetrating the air and thin and clear objects they strike against something dense and opaque, where they strike with a point and adhere to the mark the",
  "l ,r'\"\"￣ﾆ､ .,/／ ヽ、 ／ i ／ _,r\"∠ﾆ､'L- l,,／ l ,rー--－ヽ､ l / ,,r ､ ﾞl /ｦ (＿) ／⌒/",
  "success fail",
  "About this capture",
  "Internet Archive",
  "Wide Crawl started March 2011",
  "FamN, FamM, FamR",
  "��√® ‚Äö√≥√®Y",
  "ad blocking software running, please disble it",
  "±¬®� �Äö√±¬®‚Äö√ ±¬®‚Äö√±¬®� �Äö√±¬®‚Äö√±¬® ‚Äö√±¬®X?√É√©Y?‚àÜ√§v ???‚âà√á√ï√©s???‚Ä¶√≥T???w ??L???A√î√∏Œ©?A????? D?‚àÜ√á????? ???B 1787?N?‚Ä¶√á√É√ÖA?????L??? [?A?????√É√£@??`?????√� �√�",
  "�√∏Œ©√î√∏Œ©√î√� ��Œ©‚âà√á√î� ��∏Œ©√î√∏Œ© √î√∏Œ©√î√� ��Œ©‚âà√™‚Ä ∫√≠√î√∏Œ© ‚âà√á√î√∏� �©√î√∏Œ©√î√∏Œ© root√î√∏Œ©√î√∏Œ©√î� ��∏Œ©√î√∏Œ© t√î√∏Œ©√î√ ∏Œ©√î√∏Œ©� �î√∏Œ©√î√∏ Œ©√î√∏�",
  "‚Äû√Ñ√ Ñ‚Äû√Ñ√Ñ‚Äû√âŒ© _√î¬∫√†√î¬∫√∏_√� �¬∫√¢‚Äû√Ñ� ��Ñ|‚Äû√Ñ√Ñ|√î¬∫¬∫| ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ|s‚Äö√Æ√≥‚Äö√Æ‚â•‚� �ö√Æ√Ö|√î√� �¬£√î√∏¬£√� �√∏¬£√î√∏¬ £√î√∏¬£|‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ √î¬∫¬∫|. ‚Äö√Æ√á ‚Äû√Ñ√Ñ√îŒ ©√∫",
  "�î√¶� ��º√à√±√á√ä√≤√â'!! ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ . -√Ç√∏√•‚Äû√Ñ√©‚Äû√Ñ √©‚Äû√Ñ√©� �Äû√Ñ√©‚ÅÑ� �à´‚ÅÑ‚à´√î √¶√Ñ!i'√î√¶� ��ª(√îŒ©√¢√Ç¬±¬ß‚ÅÑ‚à´‚Äû√Ñ√Ñ ‚Äû�",
  ";&amp; #12288;&#12288;&#12288;&amp; #12288;&#12288;&#12288;&#12288;&#12288; ,,,iiillllllllll!!!&#65438;&#65438;&#12443; &#12288; : llllli,.\\'lllllll&#12289;&#12; 288;.,,iilll!!&#65438;liiiilllllllllll: &#65438;&#65438;!lllllllllliii,,,, ,&#12289;&#12288;&#12288; ;&#12288;&#12288;&#12288;&#12288; .,,,,iillllll!lllllll,&#12289;_,,,,,",
  "√Ñ , _ :‚Äû√Ñ√Ñ: _ ‚Äû√Ñ√Ö ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Äû� �Ñ√Ñf,√î√¶√≤l|‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ‚Ä� �√Ñ√Ñ‚Äû√â� �©__`!‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ /√î√¶√ª'√îŒ©",
  "�√≤√≠L L\\‚Äö√≤√≠‚Äö√≤√≠ ‚Äö√≤√≠‚Ä ö√≤√≠‚Äö√ ≤√≠‚Äö√≤� �≠`‚Äö√≤√≠ ‚Äö√≤√≠‚Ä ö√≤√≠‚Äö√ ≤√≠‚Äö√≤� �≠‚Äö√≤√≠� ��Äö√≤√≠‚Ä� �√≤√≠‚Äö√� ��√≠‚Äö√≤√ ≠‚Äö√≥¬∫‚ Äö√≥¬∫‚Äö� �≥¬∫‚Äö√≥¬ ∫‚Äö√≥¬∫‚ Äö√≥¬∫‚Äö� �≥¬∫‚Äö√≥¬ ∫‚Äö√≥¬∫‚ Äö√≤√≠‚Äö� ��≤√≠‚Äö√≤ √≠‚Äö√≤√� �‚Äö√≤√≠‚� �ö√≤√≠‚Äö� �≤√≠‚Äö√≤� ��≠‚Äö√≤√≠ ‚Äö√",
  "SOFTWARE UPDATTE",
  "nch that is due to the google analytics javascript, which reads user information and displays a different page profile accordingly. But I run No-Script, and AdBloc",
  "? ???`??????? ?? ?????? ?? ? ?????‚Äö√≥¬™!``/UU/‚Äö √≤√≠‚Äö√� �√≠‚Äö√≤√� ��‚Äö√≤√≠‚ Äö√≤√≠‚Äö� ��≤√≠‚Äö√≤ √≠‚Äö√≤√� �‚Äö√≤√≠‚� �ö√≤√≠‚Äö� �≥¬∫‚Äö√≤� �≠‚Äö√≤√≠� ��Äö√≤√≠‚Ä� �√≥¬∫‚Äö√≤√≠ ??? ?‚Äö√≤√≠‚Äö√≤√� �`‚Äö√≤√≠‚ Äö√≤√≠‚Äö� ��≤√≠‚Äö√≤ √≠‚Äö√≤√� �‚Äö√≤√≠‚� �ö√≤√≠‚Äö� �≤√≠",
  "to do is have them twirl around in a vortex, then \\\"flush\\\" down into a single point. I was thinking of using the vortex field to have them twirl, but I have no idea how to make them flush down in a vortex like cone to a single point. Any thoughts? Also, when i tried the vortex field, they all just exploded outwards, not twirling in a circle. Thanks",
  "�©v√î√∏ Œ©√î√∏Œ©√î √∏Œ©[√î√∏Œ ©_√î√∏Œ©√É� ��¢^√î√∏Œ©c",
  "�©√î√∏Œ©√� �√á√î√∏Œ©√ î√∏Œ©‚óä√á ‚Äö√≤√ú√î� ��∏Œ©Big-server√î √∏Œ©√î√∏Œ� �√î√∏Œ©s√î� �∏Œ©√î√∏Œ©� ��î√∏Œ©R√î√� ��Œ©[√î√∏Œ©X� ��î√∏Œ©‚âà√ á√î√∏Œ©√î� �∏Œ©B‚Äö√¥‚Ñ¢!√î√∏Œ©√î√∏Œ©√î√� ��Œ©‚âà√á√î� ��∏Œ©√î√∏Œ© √î√∏Œ©√î√� ��Œ©‚âà√™‚Ä ∫√≠√î√∏Œ© ‚âà√á√î√∏� �©√î√∏Œ©√î√∏Œ© root√î√∏Œ©√î√∏Œ©√î� ��∏Œ©√î√∏Œ© t√î√∏Œ©√î√ ∏Œ©√î√∏Œ©� �î√∏Œ©√î√∏ Œ©√î√∏Œ©√î √∏Œ©f√î√∏Œ ©B√î√∏Œ©X√",
  "�√≤√≠‚Äö√≤√≠???A???? ?U ‚Äö√≥¬Æ? m??``//////////? ? / ???????? ? ???????? ???????? ???? ?? ? ???? ???? ? ???`??????? ?? ?????? ?? ? ?????‚Äö√≥¬™!``/UU/‚Äö √≤√≠‚Äö√� �√≠‚Äö√≤√� ��‚Äö√≤√≠‚ Äö√≤√≠‚Äö� ��≤√≠‚Äö√≤",
  "� √á¬ª√á¬´√Öz?? ? ? ??? ? ??????? ?? ? ??????????√î√∏Œ©√î√∏Œ©??? ? ? ?? ? ?? ???? ?? √î√∏Œ©√î√∏Œ©√î√∏Œ© √î√∏Œ©√î√∏Œ© √î√∏Œ©? ??? ?????? ??? ????????? ? ? ? ???????? ? ?",
  "Ñ√Ñ‚Äû√ Ñ√Ñ‚Äû√Ñ√Ñ ,√îŒ©‚â§‚Äû √Ñ√Ñ./‚Äû√Ñ √Ñl‚Äû√Ñ√Ñ/l‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ √î√¶√ë,.|‚Äû√Ñ√Ñ‚Äû√� �√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ |√î¬∫√∏‚Äö√¢¬� �‚Ä∞‚àè√¢‚ Ä∞‚àè√¢‚Äö √",
  "O¬¨√Ö‚Äö√Ñ� ��∫¬¨√™¬¨¬¥‚Äö√Ñ√π\\UP! \\877 \\55,550 24‚âàŒ©‚âà√¶‚âà‚Ä†‚àö√Æ 99k/9999999999Mbps‚Äö√≥√® ‚Äö√Ñ√¨¬¨‚â •¬¨√™¬¨√ü� �âà√≠‚àö√Ñ",
  "û√Ñ√Ñ‚Ä� �√Ñ√Ñ‚Äû√Ñ√Ñ/|‚Äû√Ñ√Ñ ./|‚Äû√Ñ√Ñ‚Ä� �√Ñ√Ñ‚Äû√Ñ� ��Ñ‚Äû√Ñ√Ñ‚ Äû√Ñ√Ñ‚Äû√ Ñ√Ñ‚Äû√Ñ√Ñ ,√îŒ©‚â§‚Äû √Ñ√Ñ./‚Äû√Ñ √Ñl‚Äû√Ñ√Ñ/l‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ ‚Äû√Ñ√Ñ √î√¶√ë,.|‚Äû√Ñ√Ñ‚Äû√� �√Ñ‚Äû√Ñ√Ñ‚Äû√Ñ√Ñ |√î¬∫√∏‚Äö√¢¬� �‚Ä∞‚àè√¢‚ Ä∞‚àè√¢‚Äö √¢√ü√îŒ©√≤'|‚Äû√Ñ√Ñ/ :|‚Äû√Ñ√Ñ‚Äû� �Ñ√Ñ‚Äû√Ñ√� �‚Äû√Ñ√Ñ‚Ä� �√Ñ√Ñ‚Äû√Ñ√Ñ / ! ./ ,‚Äö√",
  "ouch it. I love to hold it. It\\'s in my pocket, right now, in iPod mode, playing that tender new Moby song through its surprisingly good little speaker and keeping my thighs warm and my heart happy. It\\'s also checking the weather in Mumbai. Incredible.\\\"",
  "�î√∏Œ©√î√∏Œ©√î√ ∏Œ©√î√∏Œ©√î√∏Œ© IJ ??¬¨¬®¬¨¬®U ! ! ! ! !",
  "ing that tender new Moby song through its surprisingly good little speaker and keeping my thighs warm and my heart happy. It\\'s also checking the weather in Mumbai. Incredible.\\\"",
  "eiserfs v3 denial of \"00000000",
  "/&gt; √î√∏Œ©√î√∏Œ©√î√� ��Œ©√î√∏Œ©‚Äû√Ñ√• ‚Äû√Ñ√Ñ√î¬∫√†� ��",
  "ö√≤√≠‚Ä� �√≤√≠‚Äö√≤√≠???A???? ?U ‚Äö√≥¬Æ? m??``//////////? ? / ???????? ? ???????? ???????? ???? ?? ? ???? ???? ? ???`??????? ?? ?????? ?? ? ?????‚Äö√≥¬™!``/UU/‚Äö √≤√≠‚Äö√� �√≠‚Äö√≤",
  "br /&gt;# insider: EHASHCOLLISION",
  "Äπ√á √ç√áŒ©?} ?e?B?",
  "@¬¨√Ö@¬¨√Ö@¬¨√Ö@¬¨√Ö@ |¬¨√ÖP¬¨√ÖP‚âà √≠‚âàŒ©‚Äö �",
  "��≥¬Æ? m??``//////////? ? / ???????? ? ???????? ???????? ???? ?? ? ???? ???? ?",
  "er the people here are real",
  "Ö@¬¨√Ö@¬¨� ��Ö@¬¨√Ö@¬¨√Ö@¬¨√Ö@¬¨√Ö@ |¬¨√ÖP¬¨√ÖP‚âà √≠‚âàŒ©‚Äö √Ñ√Æj‚",
  "Œ©√î√∏ Œ©√î√∏Œ©V√� �√∏Œ©[/√î√∏ Œ©‚àÜ√™‚Äù √á¬ª√á¬´",
  "‚Ä∫√≠√î√� �Œ©√î√∏Œ©√� �√á√î√∏Œ©√ î√∏Œ©‚óä√á ‚Äö√≤√ú√î� ��∏Œ©Big-server√î √∏Œ©√î�",
  "EVERYTHING MUST RAUS!!! - DISSOLUTION of MY EXISTENCE - partially quite rare objects",
  "P.¬¨√ò¬¨√ò¬¨√ò¬¨√� �‚àö‚àë√Ä√∫??????? ??? ??? ???? ????",
  "/&gt;„ÄÄ„ÄÄ�"
];